gamecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('games/', views.games_index, name='index'),
    path('games/<int:game_id>', views.games_detail, name='detail'),
    path('games/create/', views.GameCreate.as_view(), name='games_create'),
    path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='games_update'),
    path('games/<int:pk>/delete/', views.GameDelete.as_view(), name='games_delete'),
    path('games/<int:game_id>/add_playhistory/', views.add_playhistory, name='add_playhistory'),
    path('games/<int:game_id>/assoc_release/<int:release_id>', views.assoc_release, name='assoc_release'),
    path('games/<int:game_id>/add_photo/', views.add_photo, name='add_photo'),
    path('releases/', views.ReleaseList.as_view(), name="releases_index"),
    path('releases/<int:pk>', views.ReleaseDetail.as_view(), name="releases_detail"),
    path('releases/create/', views.ReleaseCreate.as_view(), name="releases_create"),
    path('releases/<int:pk>/update/', views.ReleaseUpdate.as_view(), name="releases_update"),
    path('releases/<int:pk>/delete/', views.ReleaseDelete.as_view(), name="releases_delete"),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Release(models.Model):
    platform = models.CharField(max_length=20)

    def __str__(self):
        return self.platform

    def get_absolute_url(self):
        return reverse('releases_detail', kwargs={'pk': self.id})

class Game(models.Model):
    title = models.CharField(max_length=100)
    genre = models.TextField(max_length=200)
    rating = models.IntegerField()
    releases = models.ManyToManyField(Release)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})
    
class Playhistory(models.Model):
    date = models.DateField('Play Date')
    playtime = models.DecimalField(max_digits=3, decimal_places=1)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return f"Played for {self.playtime} on {self.date}"

    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for game_id: {self.game_id} @{self.url}"

        

main_app/forms.py
from django.forms import ModelForm
from .models import Playhistory

class PlayhistoryForm(ModelForm):
    class Meta:
        model = Playhistory
        fields = ['date', 'playtime']

main_app/views.py
from distutils.log import Log
import os
import uuid
import boto3
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .models import Game, Release, Photo
from .forms import PlayhistoryForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def home(request):
    return render(request, 'games/index.html')

def about(request):
    return render(request, 'about.html')

@login_required
def games_index(request):
    games = Game.objects.all()
    return render(request, 'games/index.html', { 'games': games })

@login_required
def games_detail(request, game_id):
    game = Game.objects.get(id=game_id)
    releases_game_doesnt_have = Release.objects.exclude(id__in = game.releases.all().values_list('id'))
    playhistory_form = PlayhistoryForm()
    return render(request, 'games/detail.html', { 
            'game': game, 'playhistory_form': playhistory_form,
            'releases': releases_game_doesnt_have
        })

@login_required
def add_playhistory(request, game_id):
    # create a ModelForm instance using the data in request.POST
    form = PlayhistoryForm(request.POST)
    # validate the form
    if form.is_valid():
        new_playhistory = form.save(commit=False)
        new_playhistory.game_id = game_id
        new_playhistory.save()
    return redirect('detail', game_id=game_id)

@login_required
def assoc_release(request, game_id, release_id):
    Game.objects.get(id=game_id).releases.add(release_id)
    return redirect('detail', game_id=game_id)

@login_required
def add_photo(request, game_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            print(url)
            Photo.objects.create(url=url, game_id=game_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', game_id=game_id)

class GameCreate(CreateView):
    model = Game
    fields = ['title', 'genre', 'rating']
    
    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user
        return super().form_valid(form)



class GameUpdate(UpdateView):
    model = Game
    fields = ['genre', 'rating']

class GameDelete(DeleteView):
    model = Game
    success_url = '/games/'

class ReleaseList(LoginRequiredMixin, ListView):
    model = Release

class ReleaseDetail(LoginRequiredMixin, DetailView):
    model = Release

class ReleaseCreate(LoginRequiredMixin, CreateView):
    model = Release
    fields = '__all__'

class ReleaseUpdate(LoginRequiredMixin, UpdateView):
    model = Release
    fields = ['platform']

class ReleaseDelete(LoginRequiredMixin, DeleteView):
    model = Release
    success_url = '/releases/'

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Game Collector</h1>
<hr />
<p>Hire the Game Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Game Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;GameCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'releases_create' %}">Add a Platform</a></li>
            <li><a href="{% url 'releases_index' %}">View All Platform</a></li>
            <li><a href="{% url 'games_create' %}">Add a Game</a></li>
            <li><a href="{% url 'index' %}">View All My Games</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Game Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/games/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Game Detail</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ game.title }}</span>
                <p>Genre: {{ game.genre }}</p>
                {% if game.rating >= 90 %}
                    <p>⭐⭐⭐⭐⭐</p>
                {% elif game.rating >= 80 %}
                    <p>⭐⭐⭐⭐</p>
                {% elif game.rating >= 70 %}
                    <p>⭐⭐⭐</p>
                {% elif game.rating >= 60 %}
                    <p>⭐⭐</p>
                {% else %}
                    <p>⭐</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'games_update' game.id %}">Edit</a>
                <a href="{% url 'games_delete' game.id %}">Delete</a>
            </div>
        </div>
        {% for photo in game.photo_set.all %}
            <img class="responsive-img card-panel" src="{{ photo.url }}">
        {% empty %}
            <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        
        <form action="{% url 'add_photo' game.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br><br>
            <input type="submit" class="btn" value="Upload Photo">
        </form>
    </div>
    <div class="col s6">
        <form action="{% url 'add_playhistory' game.id %}" method="post">
            {% csrf_token %}
            {{ playhistory_form.as_p }}
            <input type="submit" class="btn" value="Add Playhistory">
        </form>
        <table class="striped">
            <thead>
                <tr><th>Date</th><th>Playtime</th></tr>
            </thead>
            <tbody>
                {% for history in game.playhistory_set.all %}
                    <tr>
                        <td>{{ history.date }}</td>
                        <td>{{ history.playtime }} hours</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ game.title }}'s Releases</h3>
        {% if game.releases.count %}
            {% for release in game.releases.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            {{ release.platform }}
                        </span>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>No Release Info :(</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Platforms</h3>
        {% if releases.count %}
            {% for release in releases.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            {{ release.platform }}
                        </span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'assoc_release' game.id release.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn">Add</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>{{game.name}} Already Has All Platforms Available</h5>
        {% endif %}
    </div>
</div>

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
</script>
{% endblock %}

main_app/templates/games/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Game List</h1>

{% for game in games %}
    <div class='card'>
        <a href="{% url 'detail' game.id %}">
            <div class='card-content'>
                <span class='card-title'>{{ game.title }}</span>
                <p>Description: {{ game.description }}</p>
                {% if game.rating >= 90 %}
                    <p>⭐⭐⭐⭐⭐</p>
                {% elif game.rating >= 80 %}
                    <p>⭐⭐⭐⭐</p>
                {% elif game.rating >= 70 %}
                    <p>⭐⭐⭐</p>
                {% elif game.rating >= 60 %}
                    <p>⭐⭐</p>
                {% else %}
                    <p>⭐</p>
                {% endif %}
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/games/release_form.html
{% extends 'base.html' %}
{% block content %}

<h1>Release Details</h1>

<div class="row">
    <div class="col s6 col-offset-3">
        <div class="card">
            <div class="card_content">
                <span class="card-title">{{ release.platform }}</span>
            </div>
            <div class="card-action">
                <a href="{% url 'releases_update' release.id %}">Edit</a>
                <a href="{% url 'releases_delete' release.id %}">Delete</a>
              </div>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/games/release_list.html
{% extends 'base.html %}
{% block content %}

<h1>Release List</h1>

{% for release in release_list %}
    <a href="{% url 'releases_detail' release.id %}">
        <div class="card">
            <div class="ccard-content">
                <spanclass="card-title">{{ release.platform }}u</span>
            </div>
        </div>
    </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}
{% block content%}

    <h1>Delete Game</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{object.title}}</span></h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'detail' game.id %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}
{% block content %}

    {% if object %}
        <h1>Edit <span class="teal-text">{{object.title}}</span></h1>
    {% else %}
        <h1>Add Cat</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" class="btn">
    </form>

{% endblock %}

main_app/templates/main_app/release_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

    <h1>Delete Release</h1>
    <h4>Are you sure you want to delete <span class="teal-text">{{object.name}}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'releases_detail' object.id %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/main_app/release_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Release Details</h1>

<div class="row">
    <div class="col s6 col-offset-3">
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    {{ release.platform }}
                </span>
            </div>
            <div class="card-action">
                <a href="{% url 'releases_update' release.id %}">Edit</a>
                <a href="{% url 'releases_delete' release.id %}">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/release_form.html
{% extends 'base.html' %}
{% block content %}

    {% if object %}
        <h1>Edit <span class="teal-text">{{ object.platform }}</span></h1>
    {% else %}
        <h1>Add Platform</h1>
    {% endif %}
    
    <form ation="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit!" class="btn">
    </form>

{% endblock %}

main_app/templates/main_app/release_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Release List</h1>

{% for release in release_list %}
    <a href="{% url 'releases_detail' release.id %}">
        <div class="card">
            <div class="ccard-content">
                <spanclass="card-title">{{ release.platform }}</span>
            </div>
        </div>
    </a>
{% endfor %}

{% endblock %}